language: php

# https://secure.php.net/supported-versions.php
php:
- '7.1'
- '7.2'
- '7.3'

install:
  - composer install --dev
script:
  - ./vendor/bin/phpunit
  - ./vendor/bin/phpcs .

env:
  global:
    secure: "E6Jl3i/IeWT3LsqUt48V8hv/m+oRsLQaw5Sls014H40D3o/AZueCFSVcXygrgn/OuKpcLii+9JXOoPyOCcNizgYPnTesOnJPBDDNZpFNunJOIieBNvpr/kryeu90RCJkNl9ejx0yCpzyrHeMWU1rfeyV3fbjc7AHWxKqVPphyIQ="

notifications:
  slack: opencagedata:jka26jSli6kacZMd1KimVc5k

